### ISSUE TITLE
custom variables in format breaks with guacamole

### ISSUE THREAD

**Issue by plars** [zyga/guacamole#16]
I have some extra data I want to keep track of in my logging messages:
    logging.basicConfig(
        format='%(asctime)s %(agent_name)s %(levelname)s: %(message)s')

When I try to use this with logLevel set to DEBUG though, guacamole breaks when it tries to send it's own debug log messages.
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/**init**.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/**init**.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/**init**.py", line 474, in format
    s = self._fmt % record.__dict__
KeyError: 'agent_name'
Logged from file cmdtree.py, line 178

It seems that guacamole is trying to  log debug messages when it exits without the extra data specified, but I'm not entirely sure how useful this is.  Perhaps that log message should just be removed entirely?

**Comment by plars** [comment]
For now, I'm working around this by setting my level to INFO, but I know that's no guarantee that it will work in the future.

**Comment by zyga** [comment]
```
                                                                                  This is a misuse of the logging library. There is a way to do this ‎correctly but it is independent of guacamole.                                                                                                                                                                                                                                                                                                                                        Enviat des del meu telèfon intel·ligent BlackBerry 10.                                                                                                                                                                                                                De: Paul LarsonEnviat: Friday, 11 September 2015 21:32Per a: zyga/guacamoleRespon a: zyga/guacamoleTema: Re: [guacamole] custom variables in format breaks with guacamole (#16)For now, I'm working around this by setting my level to INFO, but I know that's no guarantee that it will work in the future.
```

—Reply to this email directly or view it on GitHub.

‎

**Comment by zyga** [comment]
```
                                                                                  Please research logging context objects. They allow you to do just that. I can show you how to use them next week.                                                                                                                                                                                                                                                                                                                                        Enviat des del meu telèfon intel·ligent BlackBerry 10.                                                                                                                                                                                                                De: Paul LarsonEnviat: Friday, 11 September 2015 21:31Per a: zyga/guacamoleRespon a: zyga/guacamoleTema: [guacamole] custom variables in format breaks with guacamole (#16)I have some extra data I want to keep track of in my logging messages:
logging.basicConfig(
    format='%(asctime)s %(agent_name)s %(levelname)s: %(message)s')
```

When I try to use this with logLevel set to DEBUG though, guacamole breaks when it tries to send it's own debug log messages.
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/init.py", line 859, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/init.py", line 732, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/init.py", line 474, in format
    s = self.fmt % record.__dict_
KeyError: 'agent_name'
Logged from file cmdtree.py, line 178

It seems that guacamole is trying to  log debug messages when it exits without the extra data specified, but I'm not entirely sure how useful this is.  Perhaps that log message should just be removed entirely?

—Reply to this email directly or view it on GitHub.

**Comment by zyga** [comment]
Specifically you can use this:

``` python
import logging
logging.basicConfig(format='%(asctime)s %(agent_name)s %(levelname)s: %(message)s', level=logging.INFO)
_logger = logging.getLogger('app')
_agent_logger = logging.LoggerAdapter(_logger, {'agent_name': 'agent1'})
_agent_logger.info("Hello")
```
